[package]
name = "repcon"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
ignore = "0.4"
tempfile = "3"
dotenv = "0.15.0"

[[bin]]
name = "repcon"
path = "src/main.rs"